### ISSUE TITLE
contact athena about photos

### ISSUE THREAD

**Issue by markdav-is** [EugTech/king-pong-plan-2019#15]
we have her on the budget

**Comment by markdav-is** [comment]
Yes please!! I love that photo of olive has floated around everywhere
Did you see it's on the downtown sandwich boards this month? 
I would definitely do August if it's still available:)

**Comment by jessicabob** [comment]
Athena was emailed 8/7/19

**Comment by jessicabob** [comment]
Athena is IN! Details are being worked out.
