### ISSUE TITLE
Get PA like Mikes

### ISSUE THREAD

**Issue by markdav-is** [EugTech/king-pong-plan-2019#38]
we don't need one for July.  We can use Mike's.

but when we do, here's one for $125  

https://www.walmart.com/ip/Refurbished-ION-980069188-Audio-Total-PA-Max-Speaker/446675710

It's kind of rare, so I might buy it personally an then KP can buy it from me if I do that.

**Comment by jessicabob** [comment]
did we get this @nohorse? I thought I saw it and I was trying to org cards over here.

**Comment by markdav-is** [comment]
we totally have this
