### ISSUE TITLE
Radio Advertizing

### ISSUE THREAD

**Issue by markdav-is** [EugTech/king-pong-plan-2019#46]
please fill in the blanks on the radio advertizing bits!

stuff that needs to happen
- [ ] What the deadline for the audio bits?
- [ ] make radio bits..
- [x] what logo do they want on the shirt?
- [x] get the banner and event swag
- [ ]

**Comment by jessicabob** [comment]
@nohorse do we want to have another stand up banner for July with the Sponsor logos on it? Or a sideways one?

**Comment by markdav-is** [comment]
I think standups are fun and more bigger logos is nice for the sponsors.  I'll be at HP a few times between now and the july show if you want to work something up.
