### ISSUE TITLE
Reimburse jeronemo for gear

### ISSUE THREAD

**Issue by markdav-is** [EugTech/king-pong-plan-2019#51]

**Comment by jessicabob** [comment]
@nohorse do we have a receipt for this? or a list of what the gear is?

**Comment by markdav-is** [comment]
@jessicabob  this is a placeholder.  I know he bought some stuff and might want to get reimbursed.  I can ping him on that if you like.

**Comment by jessicabob** [comment]
PERFECT! I was just looking at the budget sheet and wanting to send things into her so that people can get paid.

**Comment by markdav-is** [comment]
I don't get the impression he wants to get any money back
