### ISSUE TITLE
reimburse mark for screen

### ISSUE THREAD

**Issue by markdav-is** [EugTech/king-pong-plan-2019#7]
- [x] get reciept
- [x] submit to TAOF
- [x] get paid

**Comment by jessicabob** [comment]
@nohorse Are we waiting until the end of the season to do this one or is it just off the radar?

**Comment by markdav-is** [comment]
I think we can wait until the end for this one. if there is anything left over.  the projector was the big ticket item

**Comment by markdav-is** [comment]
this was part of the projector payment in my book
